import swaggerAutogen from "swagger-autogen";
import "dotenv/config";

const swaggerAuto = swaggerAutogen();
const outputFile = "./public/swagger.json";
const endpointsFiles = ["./src/routes/gateway.route.js"];

const port = process.env.PORT || 3002;
//swaggerAuto(outputFile, endpointsFiles);

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: `localhost:${port}`,
  basePath: "/gateway",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Gateway",
      description: "Musala Gateway API",
    },
  ],
};

swaggerAuto(outputFile, endpointsFiles, doc).then(() => {
  ["./index.js"];
});
