name: build-and-test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - master
      - releases/*
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: "./package-lock.json"
      - run: npm install
      - run: npm run test
      - run: npm run start
